### ISSUE TITLE
Possible to add Grafana datasource + dashboard

### ISSUE THREAD

**Issue by benbender** [ncarlier/za#1]
Hey,

very nice looking project - would it be possible for you to add your grafana configs (as seen on the screenshot) to the project?
Would be nice to have "ready to go solution"...

Thanks!

**Comment by ncarlier** [comment]
Hi,

here the Grafana configuration used for the example: https://github.com/ncarlier/za/blob/master/dashboard/grafana-loki_example.json

Regards.

**Comment by benbender** [comment]
Thank you very much for the work in general and the fast addition!
