### ISSUE TITLE
“Frequent ‘ResizeObserver loop completed with undelivered notifications’ Warnings in Console”

### ISSUE THREAD

**Issue by tiansin** [ncarlier/za#9]
<img width="1363" alt="1" src="https://github.com/user-attachments/assets/a47f2f63-19bc-4de9-adb9-8f9fc74afd4d">

**Comment by ncarlier** [comment]
I think you've enabled unhandled exception events (with `za('send', 'error')`). Your website (using React) seems to produce a lot of errors. BTWs a well-known React error:  https://sentry.io/answers/react-resizeobserver-loop-completed-with-undelivered-notifications/
On ZerØ Analytics's side you can ignore this event using [conditions]()ttps://github.com/ncarlier/za?tab=readme-ov-file#condition. But the best option should be to fix the issue on your website.

**Comment by tiansin** [comment]
I noticed that changes made to the http section for matching are not taking effect. This seems to be because the http section is not being parsed correctly at the location referenced [here](https://github.com/ncarlier/za/blob/138b320db24f2432f331b5ab5394a3438648778b/pkg/config/loader.go#L33). Could this be related to how the parsing is handled?

**Comment by ncarlier** [comment]
You are right. It's fixed. Thanks.
